name: CI (Nightly)

on:
  schedule:
    - cron: '30 5 * * *'
  workflow_dispatch:

jobs:
  jest-test:
    uses: ./.github/workflows/jest-test.yaml
    
  create-timestamp:
    uses: ./.github/workflows/create-timestamp.yaml
    
  create-cache-key:
    uses: ./.github/workflows/create-cache-key.yaml
    
  android-build:
    strategy:
      matrix:
        arch: [ x86_64, x86, arm64-v8a, armeabi-v7a ]
      fail-fast: false
    uses: ./.github/workflows/android-build.yaml
    needs: create-cache-key
    with:
      cache-key: ${{ needs.create-cache-key.outputs.cache-key }}
      arch: ${{ matrix.arch }}

  android-macos-integration-test:
    strategy:
      matrix:
        arch: [armeabi-v7a]
    uses: ./.github/workflows/android-macos-integration-test.yaml
    needs: [ create-timestamp, create-cache-key, android-build ]
    with:
      timestamp: ${{ needs.create-timestamp.outputs.timestamp }}
      cache-key: ${{ needs.create-cache-key.outputs.cache-key }}
      abi: ${{ matrix.arch }}

  android-ubuntu-integration-test-ci:
    strategy:
      matrix:
        config:
          - { abi: x86_64, api-level: 34 }
          - { abi: x86, api-level: 29 }
          - { abi: arm64-v8a, api-level: 30 }
      fail-fast: false
    uses: ./.github/workflows/android-ubuntu-integration-test-ci.yaml
    needs: [create-timestamp, android-build]
    with:
      timestamp: ${{ needs.create-timestamp.outputs.timestamp }}
      cache-key: ${{ needs.create-cache-key.outputs.cache-key }}
      abi: ${{ matrix.config.abi }}
      api-level: ${{ matrix.config['api-level'] }}

  ios-build:
    strategy:
      fail-fast: false
    uses: ./.github/workflows/ios-build.yaml
    needs: create-cache-key
    with:
      cache-key: ${{ needs.create-cache-key.outputs.cache-key }}
       
  ios-integration-test:
    strategy:
      fail-fast: false
    uses: ./.github/workflows/ios-integration-test.yaml
    needs: [ create-timestamp, ios-build ]
    with:
      timestamp: ${{ needs.create-timestamp.outputs.timestamp }}
      cache-key: ${{ needs.create-cache-key.outputs.cache-key }}